### ISSUE TITLE
First class promise support

### ISSUE THREAD

**Issue by benquarmby** [itsananderson/kudu-api#15]
As a consumer, it's relatively straight forward to wrap promises around any package that uses standard Node.js callback patterns. For example, using Bluebird's `promisify` and `promisifyAll`. These already work with kudu-api, but the support could be better.

``` JavaScript
var Promise = require("bluebird");
var kuduApi = require("kudu-api")(credentials);
var vfs = Promise.promisifyAll(kuduApi.vfs);
```

The issue is that promises must resolve to a single value, but kudu-api generally resolves two discreet values on success; for example JSON data and the raw response so headers and other artifacts can be retrieved. To get both pieces of data in a Promise, it must resolve to an array which is quite awkward to work with:

``` JavaScript
var vfs = Promise.promisifyAll(kuduApi.vfs, {
    multiArgs: true
});

vfs.listFilesAsync("site/wwwroot")
    .then(function (args) {
        var data = args[0];
        var response = args[1];

        // Work with data and response
    });
```

I'm hoping we can improve the story here.

**Comment by itsananderson** [comment]
This makes sense. It could be nice to expose a promise-based API under `require("kudu-api/promise")` or something, but you're right that the API doesn't quite lend itself to that.

What if we changed the callbacks to always have `err, result` and let `result` be a dynamic object that can contain `data`, `stream`, etc. along with the `response` object.

```javascript
var vfs = Promise.promisifyAll(kuduApi.vfs, {
    multiArgs: true
});

vfs.listFilesAsync("site/wwwroot")
    .then(function (result) {
        var data = result.data;
        var response = result.response;

        // Work with data and response
    });
```

The move to 2.0 seems like the ideal time to do this, since we'd already be introducing breaking changes.

**Comment by benquarmby** [comment]
I like that proposal. On the negative side, nesting makes consuming data a touch more awkward. But on the positive side the API will be completely consistent and predictable (always the same number of arguments), promise friendly and future proof! I think it's worth the effort.

About 2.0; yes absolutely, that's why I wanted to raise it now :)
